apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhoni-on-strike-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhoni-on-strike
  template:
    metadata:
      labels:
        app: dhoni-on-strike
    spec:
      containers:
      - name: dhoni-on-strike-container
        image: psshri/dhoni_on_strike:python-v1.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: dhoni-on-strike-configmap