apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhoni-on-strike-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhoni-on-strike
  template:
    metadata:
      labels:
        app: dhoni-on-strike
    spec:
      containers:
      - name: dhoni-on-strike-container
        image: psshri/dhoni_on_strike:golang-v1.0
        imagePullPolicy: IfNotPresent
        # envFrom:
        # - configMapRef:
        #     name: dhoni-on-strike-configmap
        env:
          - name: PLAYER_ID
            valueFrom:
              configMapKeyRef:
                name: dhoni-on-strike-configmap
                key: player_id
          - name: PLAYER_NAME
            valueFrom:
              configMapKeyRef:
                name: dhoni-on-strike-configmap
                key: player_name
          - name: TEAM_ID
            valueFrom:
              configMapKeyRef:
                name: dhoni-on-strike-configmap
                key: team_id
          - name: TEAM_NAME
            valueFrom:
              configMapKeyRef:
                name: dhoni-on-strike-configmap
                key: team_name
          - name: INTERVAL
            valueFrom:
              configMapKeyRef:
                name: dhoni-on-strike-configmap
                key: interval